name: ci

permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    tags: '*'
  pull_request:
    branches: '**'
  merge_group:
    types: [checks_requested]


jobs:
  go_test:
    name: go test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit # Audit network and disk activity

    - name: Check out code
      id: checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version-file: './go.mod'
        check-latest: true
        cache: false

    - id: go-cache-paths
      shell: bash
      run: |
        echo "go-build=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
        echo "go-mod=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"

    - name: cache restore - GOCACHE
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        enableCrossOsArchive: true

    - name: cache restore - GOMODCACHE
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        enableCrossOsArchive: true

    - name: Short Test
      shell: bash
      run: go test -cover -coverprofile=coverage.out -short -timeout 10m ./...

    - name: Race Test
      run: go test -timeout 10m -race -run "TestDB_(Concurrent|GoleveldbIssue74)" ./leveldb

    - name: Upload coverage
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ runner.os }}-coverage.out
        path: ./coverage.out
        if-no-files-found: error

  ci_mergeable:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit # Audit network and disk activity

      - run: true
    needs:
      - go_test
